spring:
  application:
    name: db_service

server:
  port: 8301


#####################
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
  instance:
    preferIpAddress: false
