spring:
  application:
    name: eureka-server

server:
  port: 8300


#####################

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8300/eureka/

#####################

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    db_service:
      path: /db-service/**
      url: http://localhost:8301
    stock_service:
      path: /stock-service/**
      url: http://localhost:8302

